##################################################################
# Sliders Page for different use cases

# Init labels for each slider
automation: 
  - alias: hasp_plate01_p4_SlidersInit
    trigger: 
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    action:
    #Text/font slider1  
      - service: mqtt.publish
        data:
          topic: 'hasp/plate01/command/p[4].b[3].font'
          payload: '7'
      - service: mqtt.publish
        data:
          topic: 'hasp/plate01/command/p[4].b[3].txt'
          payload_template: "{{ state_attr('group.wz_decke', 'friendly_name') }}"
    #Text/font slider2 
      - service: mqtt.publish
        data:
          topic: 'hasp/plate01/command/p[4].b[4].font'
          payload: '7'
      - service: mqtt.publish
        data:
          topic: 'hasp/plate01/command/p[4].b[4].txt'
          payload_template: "{{ state_attr('light.light_2', 'friendly_name') }}"
    #Text/font slider3
      - service: mqtt.publish
        data:
          topic: 'hasp/plate01/command/p[4].b[5].font'
          payload: '7'
      - service: mqtt.publish
        data: 
          topic: 'hasp/plate01/command/p[4].b[5].txt'
          payload_template: "{{ state_attr('light.light_3', 'friendly_name') }}"

##############################################################################################
# Set value in HASS when slider in HASP changes

  - alias: hasp_plate01_p4_Slider1UpdateHass
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[4].b[6].val'
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.light_1
        brightness_pct: '{{ trigger.payload }}'

  - alias: hasp_plate01_p4_Slider2UpdateHass
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[4].b[7].val'
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.light_2
        white_value: '{{ trigger.payload }}'

  - alias: hasp_plate01_p4_Slider3UpdateHass
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[4].b[8].val'
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.light_3
        brightness_pct: '{{ trigger.payload }}'