##############################################################################
# Automations for handling the 3 page select buttons at the bottom of each
# page on the panel.

automation:
##############################################################################
# Restore saved page on connect
  - alias: hasp_plate01_p0_RestoreActivePage
    trigger:
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/page'
        payload_template: '{{states.input_number.hasp_plate01_activepage.state|int}}'

##############################################################################
# select hasp_plate01_pagebutton1page in response to page button 1
  - alias: hasp_plate01_p0_PageButton1Action
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[6].b[1]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/plate01/state/p[8].b[1]'
      payload: 'ON'
    action:
    - service: input_number.set_value
      data_template:
        entity_id: 'input_number.hasp_plate01_activepage'
        value: '{{states.input_number.hasp_plate01_pagebutton1page.state|int}}'
      
##############################################################################
# select hasp_plate01_pagebutton2page in response to page button 2
  - alias: hasp_plate01_p0_PageButton2Action
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[3].b[2]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/plate01/state/p[8].b[2]'
      payload: 'ON'
    action:
    - service: input_number.set_value
      data_template:
        entity_id: 'input_number.hasp_plate01_activepage'
        value: '{{states.input_number.hasp_plate01_pagebutton2page.state|int}}'
      
##############################################################################
# select hasp_plate01_pagebutton3page in response to page button 3
  - alias: hasp_plate01_p0_PageButton3Action
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[3].b[3]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/plate01/state/p[6].b[3]'
      payload: 'ON'
    action:
    - service: input_number.set_value
      data_template:
        entity_id: 'input_number.hasp_plate01_activepage'
        value: '{{states.input_number.hasp_plate01_pagebutton3page.state|int}}'

##############################################################################
# Go back to the Menu if Back button gets pressed
  - alias: hasp_plate01_p0_BackButtonAction
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[2].b[1]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/plate01/state/p[4].b[1]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/plate01/state/p[5].b[1]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/plate01/state/p[9].b[1]'
      payload: 'ON'
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/page'
        payload: '1'

##############################################################################
# Go back to the Home/Weather page if Home button gets pressed
  - alias: hasp_plate01_p0_HomeButtonAction
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[2].b[2]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/plate01/state/p[4].b[2]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/plate01/state/p[5].b[2]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].b[2]'
      payload: 'ON'
    - platform: mqtt
      topic: 'hasp/plate01/state/p[9].b[2]'
      payload: 'ON'
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/page'
        payload: '3'

##############################################################################
# Update hasp_plate01_p0_active_page when changed at the panel
  - alias: hasp_plate01_p0_PanelPageChanged
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/page'
    action:
    - service: automation.turn_off
      entity_id: automation.hasp_plate01_p0_ActivePageSliderChanged
    - service: input_number.set_value
      data_template:
        entity_id: input_number.hasp_plate01_activepage
        value: '{{ trigger.payload }}'
    - service: automation.turn_on
      entity_id: automation.hasp_plate01_p0_ActivePageSliderChanged

##############################################################################
# Change page at panel when hasp_plate01_p0_active_page updated
  - alias: hasp_plate01_p0_ActivePageSliderChanged
    trigger:
    - platform: state
      entity_id: input_number.hasp_plate01_activepage
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/page'
        payload: '{{ states.input_number.hasp_plate01_activepage.state|int }}'


