##############################################################################
# Out of the box the Media Player page uses Spotify as component.
# If you are using a different Media Player, 
# replace every media_player.spotify with your Media Player component
sensor:
  - platform: template
    sensors:
      media_player_title:
        value_template: '{{ states.media_player.spotify.attributes.media_title }}'
      media_player_artist:
        value_template: '{{ states.media_player.spotify.attributes.media_artist }}'
      media_player_volume:
        value_template: '{{ states.media_player.spotify.attributes.volume_level }}'


automation:
##############################################################################
# Open Playlists when pressing Media Player button in NavBar
  - alias: hasp_plate01_p8_OpenPlaylistPage
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[8].b[3]'
      payload: 'ON'
    action:
    - service: input_number.set_value
      data_template:
        entity_id: 'input_number.hasp_plate01_activepage'
        value: '7'

##############################################################################
# Automations to display media player info on page 8

# Initialize button text/font/pictures for media page
#  - alias: hasp_plate01_p8_MediaInit
#    trigger:
#    - platform: state
#      entity_id: 'binary_sensor.plate01_connected'
#      to: 'on'
#    - platform: homeassistant
#      event: start
#    action:
#    - service: mqtt.publish
#      data:
#        topic: 'hasp/plate01/command/p[8].b[8].pic'
#        payload: '22'


  # Play/Pause button action
  - alias: hasp_plate01_p8_MediaPauseButton6
    trigger:
      platform: mqtt
      topic: 'hasp/plate01/state/p[8].b[6]'
      payload: 'ON'
    action:
      service: media_player.media_play_pause
      entity_id: media_player.spotify
  
  # Prev Track button action
  - alias: hasp_plate01_p8_MediaPrevTrackButton5
    trigger:
      platform: mqtt
      topic: 'hasp/plate01/state/p[8].b[5]'
      payload: 'ON'
    action:
      service: media_player.media_previous_track
      entity_id: media_player.spotify
      
  # Next Track button action
  - alias: hasp_plate01_p8_MediaNextTrackButton7
    trigger:
      platform: mqtt
      topic: 'hasp/plate01/state/p[8].b[7]'
      payload: 'ON'
    action:
      service: media_player.media_next_track
      entity_id: media_player.spotify
      
  # Scale media information fonts to fit
  # 0 consolas 24 - 20 chars x 2 lines (wrapped)
  # 1 consolas 32 - 15 chars x 2 lines (wrapped)
  # 2 consolas 48 - 10 chars x 1 line
  # 3 consolas 80 - 6 chars x 1 line
  - alias: hasp_plate01_p8_MediaArtist
    trigger:
    - platform: state
      entity_id: sensor.media_player_artist
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[8].b[4].font'
        payload_template: '{% if states.sensor.media_player_artist.state|length <= 6 -%}3{% elif (states.sensor.media_player_artist.state|length > 6) and (states.sensor.media_player_artist.state|length <= 10) %}2{% elif (states.sensor.media_player_artist.state|length > 10) and (states.sensor.media_player_artist.state|length <= 15) %}1{% else %}0{%- endif %}'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[8].b[4].txt'
        payload_template: '"{{ states.sensor.media_player_artist.state|wordwrap(20, wrapstring="\\r") }}"'
  
  - alias: hasp_plate01_p8_ScrollingMediaTitle
    trigger:
    - platform: state
      entity_id: sensor.media_player_title
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[8].b[9].font'
        payload_template: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[8].b[9].txt'
        payload_template: '"{{ states.sensor.media_player_title.state|wordwrap(20, wrapstring="\\r") }}"'
  
  - alias: hasp_plate01_p8_MediaPlayPause
    trigger:
    - platform: state
      entity_id: media_player.spotify
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[8].b[6].picc'
        payload_template: >-
          {% if states.media_player.spotify.state == "playing" -%}
            {{ 3 }}
          {%- elif states.media_player.spotify.state == "paused" -%}
            {{ 4 }}
          {% endif -%}
  
  # Volume slider value published, apply published state
  - alias: hasp_plate01_p8_MediaVolSliderUpdateHass
    trigger:
      platform: mqtt
      topic: 'hasp/plate01/state/p[8].b[8].val'
    action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.spotify
        volume_level: '{{ (trigger.payload|int) / 100 }}'
        
  # Volume slider value changed by hass, update HASP 
  - alias: hasp_plate01_p8_MediaVolSliderUpdateHASP 
    trigger:
    - platform: state
      entity_id: sensor.media_player_volume
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[8].b[8].val'
        payload_template: '{{ (states.sensor.media_player_volume.state | float * 100) | int }}'
