
#####################################
automation:
  - alias: hasp_plate01_p2_accessmenu
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[3].b[1]'
      payload: 'ON'
    action:
    - service: input_number.set_value
      data: 
        entity_id: 'input_number.hasp_plate01_activepage'
        value: '1'
        
##########################################
# Set labels for each button
  
  # Initialize button labels
  - alias: hasp_plate01_p2_ButtonInit
    trigger:
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
      
    action:   
      
      # Label - Scene 1
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[2].b[12].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[2].b[12].txt'
        payload: '"Script1"'
     
     # Label - Scene 2
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[2].b[11].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[2].b[11].txt'
        payload: '"Script2"'
      
# Label - Scene 3
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[2].b[10].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[2].b[10].txt'
        payload: '"Fernsehen"'
    
    # Label - Scene 4
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[2].b[9].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[2].b[9].txt'
        payload: '"Essen"'

    # Label - Scene 5
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[2].b[8].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[2].b[8].txt'
        payload: '"Kochen"'

#####################################
#  Switch to page on button press
# Back button 
  - alias: hasp_plate01_p2_BackButtonAction
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[2].b[1]'
      payload: 'ON'
    action:
    - service: mqtt.publish
      data:     
        topic: 'hasp/plate01/command/page'
        payload: '1'

# Home Button
  - alias: hasp_plate01_p2_BackButtonAction
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[2].b[2]'
      payload: 'ON'
    action:
    - service: mqtt.publish
      data:     
        topic: 'hasp/plate01/command/page'
        payload: '3'     

# Scene 1
  - alias: hasp_plate01_p2_Scene1Action
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[2].b[3]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.DUMMY

# Scene 2    
  - alias: hasp_plate01_p2_ThermostatButtonAction
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[2].b[4]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.DUMMY

# Scene 3
  - alias: hasp_plate01_p2_PlaylistsButtonAction
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[2].b[5]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.routine_fernsehen
      
# Scene 4     
  - alias: hasp_plate01_p2_ScenesButtonAction
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[2].b[6]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.routine_mahlzeit

# Scene 5    
  - alias: hasp_plate01_p2_ScenesButtonAction
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[2].b[7]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.routine_kochen
        
  
        