###########################################################################
# Scripts to setup up playlists for the playlists page,
# accessed by pressing the media_player button
# if already on media_player page
# To use the scripts replace USER and PLAYLIST_ID in media_content_id
# with the user and id of your desired playlist.
# For further instructions how to get the needed ID 
# visit: https://support.spotify.com/us/article/sharing-music/

script:
#Playlist 1
  hasp_spotify_playlist_1:
    alias: 'Playlist 1'
    sequence:
      - service: media_player.play_media
        data_template:
          entity_id: media_player.spotify
          media_content_id: 'spotify:user:USER:playlist:PLAYLIST_ID'
          media_content_type: playlist

#Playlist 2
  hasp_spotify_playlist_2:
    alias: 'Playlist 2'
    sequence:
      - service: media_player.play_media
        data_template:
          entity_id: media_player.spotify
          media_content_id: 'spotify:user:USER:playlist:PLAYLIST_ID'
          media_content_type: playlist

#Playlist 3
hasp_spotify_playlist_3:
    alias: 'Playlist 3'
    sequence:
      - service: media_player.play_media
        data_template:
          entity_id: media_player.spotify
          media_content_id: 'spotify:user:USER:playlist:PLAYLIST_ID'
          media_content_type: playlist

#Playlist 4
hasp_spotify_playlist_4:
    alias: 'Playlist 4'
    sequence:
      - service: media_player.play_media
        data_template:
          entity_id: media_player.spotify
          media_content_id: 'spotify:user:USER:playlist:PLAYLIST_ID'
          media_content_type: playlist

#Playlist 5
hasp_spotify_playlist_5:
    alias: 'Playlist 5'
    sequence:
      - service: media_player.play_media
        data_template:
          entity_id: media_player.spotify
          media_content_id: 'spotify:user:USER:playlist:PLAYLIST_ID'
          media_content_type: playlist

#Playlist 6
hasp_spotify_playlist_6:
    alias: 'Playlist 6'
    sequence:
      - service: media_player.play_media
        data_template:
          entity_id: media_player.spotify
          media_content_id: 'spotify:user:USER:playlist:PLAYLIST_ID'
          media_content_type: playlist


#############################################################################
automation:
  #Set font and text for toggle buttons on device connection
  - alias: hasp_plate01_p7_ToggleInit
    trigger:
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: mqtt
      topic: 'hasp/plate01/state/page'
      payload: '7'
    - platform: state
      entity_id: 'input_number.hasp_plate01_activepage'
      to: '7'
    action:
    # Font/text Playlist 1
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[3].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[3].txt'
        payload_template: "{{ state_attr('script.hasp_spotify_playlist_1', 'friendly_name') }}"
    #Font/text Playlist 2
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[4].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[4].txt'
        payload_template: "{{ state_attr('script.hasp_spotify_playlist_2', 'friendly_name') }}"
    #Font/text Playlist 3
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[5].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[5].txt'
        payload_template: "{{ state_attr('script.hasp_spotify_playlist_3', 'friendly_name') }}"
    #Font/text Playlist 4
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[6].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[6].txt'
        payload_template: "{{ state_attr('script.hasp_spotify_playlist_4', 'friendly_name') }}"
    #Font/text Playlist 5
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[7].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[7].txt'
        payload_template: "{{ state_attr('script.hasp_spotify_playlist_5', 'friendly_name') }}"
    #Font/text Playlist 6
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[8].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[8].txt'
        payload_template: "{{ state_attr('script.hasp_spotify_playlist_6', 'friendly_name') }}"

########################################################################
#Switch to playlist on button press
  #Activate Playlist1
  - alias: hasp_plate01_p7_ActivatePlaylist1
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].b[9]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.hasp_spotify_playlist_1

  #Activate Playlist2
  - alias: hasp_plate01_p7_ActivatePlaylist2
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].b[10]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data    :
        entity_id: script.hasp_spotify_playlist_2

  #Acitvate Playlist3
  - alias: hasp_plate01_p7_ActivatePlaylist3
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].b[11]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data    :
        entity_id: script.hasp_spotify_playlist_3

  #Activate Playlist4
  - alias: hasp_plate01_p7_ActivatePlaylist4
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].b[12]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data    :
        entity_id: script.hasp_spotify_playlist_4

  #Activate Playlist5
  - alias: hasp_plate01_p7_ActivatePlaylist5
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].b[13]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data    :
        entity_id: script.hasp_spotify_playlist_5

  #Activate Playlist6
  - alias: hasp_plate01_p7_ActivatePlaylist6
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].b[14]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data    :
        entity_id: script.hasp_spotify_playlist_6
