

# Automations to display the weather forecast and current temp on page 2

automation:
  # Display weather details on page 3 when weather updates or on HASP init
  - alias: hasp_plate01_p3_Weather
    trigger:
    - platform: state
      entity_id: input_boolean.hasp_plate01_p3_temperatureswitch
    - platform: state
      entity_id: sensor.YOUR_TEMPERATURE_SENSOR
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
    - platform: homeassistant
      event: start
    condition:
    - condition: state
      entity_id: 'binary_sensor.plate01_connected'
      state: 'on'
    action:
    # In Text
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[9].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[9].txt'
        payload: {{ In }}

    # In Temp
    
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[6].font'
        payload: '5'
# Replace sensor.YOUR_TEMPERATURE_SENSOR with your temperature sensor
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[6].txt'
        payload_template: '"{{ states.sensor.YourTemperatureSensor.state }}°C"'
       

    # In Humidity
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[11].font'
        payload: '7'
# Replace sensor.YOUR_HUMIDITY_SENSOR with your humidity sensor
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[11].txt'
        payload_template: '"{{ states.sensor.YourHumiditySensor.state }}%"'

    # Out
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[10].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[10].txt'
        payload_template: '"Aussen"'
    # Out Temp
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[7].font'
        payload: '5'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[7].txt'
        payload_template: '"{{ states.sensor.dark_sky_temperature.state }}°C"'

    # Out Humidity
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[12].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[12].txt'
        payload_template: '"{{ states.sensor.dark_sky_humidity.state }}%"'

# Forecast
  # Now Label
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[16].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[16].txt'
        payload_template: '"Now"'
# Icon Now
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[3].b[13].pic'
        payload_template: >-
          {% if states.sensor.dark_sky_icon.state == "clear-day" -%}
            {{ 16 }}
          {%- elif states.sensor.dark_sky_icon.state == "clear-night" -%}
            {{ 20 }}
          {%- elif states.sensor.dark_sky_icon.state == "rain" -%}
            {{ 13 }}
          {%- elif states.sensor.dark_sky_icon.state == "partly-cloudy-day" -%}
            {{ 14 }}
          {%- elif states.sensor.dark_sky_icon.state == "partly-cloudy-night" -%}
            {{ 15 }}
          {%- elif states.sensor.dark_sky_icon.state == "fog" -%}
            {{ 19 }}
          {%- elif states.sensor.dark_sky_icon.state == "snow" -%}
            {{ 17 }}
          {%- elif states.sensor.dark_sky_icon.state == "sleet" -%}
            {{ 18 }}
          {%- endif %}

  # 24h
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[17].font'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[17].txt'
        payload_template: '"{{(as_timestamp(now())+ (86400)) | timestamp_custom("%a",true)}}"'
    #Icon  24h
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[14].font'
        payload: '7'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[3].b[14].pic'
        payload_template: >-
          {% if states.sensor.dark_sky_icon_2.state == "clear-day" -%}
            {{ 16 }}
          {%- elif states.sensor.dark_sky_icon_2.state == "clear-night" -%}
            {{ 20 }}
          {%- elif states.sensor.dark_sky_icon_2.state == "rain" -%}
            {{ 13 }}
          {%- elif states.sensor.dark_sky_icon_2.state == "partly-cloudy-day" -%}
            {{ 14 }}
          {%- elif states.sensor.dark_sky_icon_2.state == "partly-cloudy-night" -%}
            {{ 15 }}
          {%- elif states.sensor.dark_sky_icon_2.state == "fog" -%}
            {{ 19 }}
          {%- elif states.sensor.dark_sky_icon_2.state == "snow" -%}
            {{ 17 }}
          {%- elif states.sensor.dark_sky_icon_2.state == "sleet" -%}
            {{ 18 }}
          {%- endif %}

  # 48h
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[18].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[3].b[18].txt'
        payload_template: '"{{(as_timestamp(now())+ (172800)) | timestamp_custom("%a",true)}}"'

    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/p[3].b[15].pic'
        payload_template: >-
          {% if states.sensor.dark_sky_icon_3.state == "clear-day" -%}
            {{ 16 }}
          {%- elif states.sensor.dark_sky_icon_3.state == "clear-night" -%}
            {{ 20 }}
          {%- elif states.sensor.dark_sky_icon_3.state == "rain" -%}
            {{ 13 }}
          {%- elif states.sensor.dark_sky_icon_3.state == "partly-cloudy-day" -%}
            {{ 14 }}
          {%- elif states.sensor.dark_sky_icon_3.state == "partly-cloudy-night" -%}
            {{ 15 }}
          {%- elif states.sensor.dark_sky_icon_3.state == "fog" -%}
            {{ 19 }}
          {%- elif states.sensor.dark_sky_icon_3.state == "snow" -%}
            {{ 17 }}
          {%- elif states.sensor.dark_sky_icon_3.state == "sleet" -%}
            {{ 18 }}
          {%- endif %}


