automation:
  #Set font and text for toggle buttons on device connection
  - alias: hasp_plate01_p7_ToggleInit
    trigger:
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: mqtt
      topic: 'hasp/plate01/state/page'
      payload: '7'
    - platform: state
      entity_id: 'input_number.hasp_plate01_activepage'
      to: '7'
    action:
    # Font/text Toggle 1/9
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[3].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[3].txt'
        payload_template: '\"{{ state_attr("script.PLAYLIST1", "friendly_name")}}\"'
    #Font/text Toggle 2/10
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[4].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[4].txt'
        payload_template: '\"{{ state_attr("script.PLAYLIST2", "friendly_name") }}\"'
    #Font/text Toggle 3/11
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[5].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[5].txt'
        payload_template: '"{{ state_attr("script.PLAYLIST3", "friendly_name") }}"'
    #Font/text Toggle 4/12
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[6].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[6].txt'
        payload_template: '"{{ state_attr("script.PLAYLIST4", "friendly_name") }}"'
    #Font/text Toggle 5/13
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[7].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[7].txt'
        payload_template: '"{{ state_attr("script.PLAYLIST5", "friendly_name") }}"'
    #Font/text Toggle 6/14
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[8].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[8].txt'
        payload_template: '"{{ state_attr("script.PLAYLIST6", "friendly_name") }}"'

########################################################################
#Switch to playlist on button press
  #Activate Playlist1
  - alias: hasp_plate01_p7_ActivatePlaylist1
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].b[3]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.PLAYLIST1

  #Activate Playlist2
  - alias: hasp_plate01_p7_ActivatePlaylist2
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].b[4]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.PLAYLIST2

  #Acitvate Playlist3
  - alias: hasp_plate01_p7_ActivatePlaylist3
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].b[5]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.PLAYLIST3

  #Activate Playlist4
  - alias: hasp_plate01_p7_ActivatePlaylist4
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].b[6]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.PLAYLIST4

  #Activate Playlist5
  - alias: hasp_plate01_p7_ActivatePlaylist5
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].b[7]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.PLAYLIST5

  #Activate Playlist6
  - alias: hasp_plate01_p7_ActivatePlaylist6
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].b[8]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.PLAYLIST6
