##############################################################################
# Automations for handling the 3 page select buttons at the bottom of each
# page on the panel.

automation:
##############################################################################
# Restore saved page on connect
  - alias: hasp_plate01_p0_RestoreActivePage
    trigger:
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/page'
        payload_template: '{{states.input_number.hasp_plate01_activepage.state|int}}'

##############################################################################
# Update hasp_plate01_p0_active_page when changed at the panel
  - alias: hasp_plate01_p0_PanelPageChanged
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/page'
    action:
    - service: automation.turn_off
      entity_id: automation.hasp_plate01_p0_ActivePageSliderChanged
    - service: input_number.set_value
      data_template:
        entity_id: input_number.hasp_plate01_activepage
        value: '{{ trigger.payload }}'
    - service: automation.turn_on
      entity_id: automation.hasp_plate01_p0_ActivePageSliderChanged

##############################################################################
# Change page at panel when hasp_plate01_p0_active_page updated
  - alias: hasp_plate01_p0_ActivePageSliderChanged
    trigger:
    - platform: state
      entity_id: input_number.hasp_plate01_activepage
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate01/command/page'
        payload: '{{ states.input_number.hasp_plate01_activepage.state|int }}'
      
