#####################################
automation:
        
##########################################
# Set labels for each button
  
  # Initialize button labels
  - alias: hasp_plate01_p1_ButtonInit
    trigger:
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
      
    action:   
    # Text/font Home button
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[1].b[5].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[1].b[5].txt'
        payload: '"Home"'
        
    # Text/font Sliders label
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[1].b[4].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[1].b[4].txt'
        payload: '"Sliders"'
      
    # Text/font Menu Button Thermostat label
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[1].b[3].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[1].b[3].txt'
        payload: '"Thermostat"'
     
    # Text/font menu button Playlist label
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[1].b[2].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[1].b[2].txt'
        payload: '"Playlist"'
      
    # Text/font Label - button scenes
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[1].b[1].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[1].b[1].txt'
        payload: '"Scenes"'

