automation:
#Go back to the Media Page by pressing the back button
  - alias: hasp_plate01_p7_BackButtonAction
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].b[1]'
      payload: 'ON'
    action:
    - service: input_number.set_value
      data_template:
        entity_id: 'input_number.hasp_plate01_activepage'
        value: '8'

  #Set font and text for toggle buttons on device connection
  - alias: hasp_plate01_p7_ToggleInit
    trigger:
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: 'input_number.hasp_plate01_activepage'
      to: '7'
    action:
    # Font/text Toggle 1/9
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].p[3].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[3].txt'
        payload: '"Playlist 1"'
    #Font/text Toggle 2/10
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[4].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[4].txt'
        payload: '"Playlist 2"'
    #Font/text Toggle 3/11
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[5].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[5].txt'
        payload: '"Playlist 3"'
    #Font/text Toggle 4/12
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[6].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[6].txt'
        payload: '"Playlist 4"'
    #Font/text Toggle 5/13
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[7].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[7].txt'
        payload: '"Playlist 5"'
    #Font/text Toggle 6/14
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[8].font'
        payload: '7'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/p[7].b[8].txt'
        payload: '"Playlist 6"'

########################################################################
#Switch to playlist on button press
  #Activate Playlist1
  - alias: hasp_plate01_p7_ActivatePlaylist1
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].p[3]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.spotify_PLAYLIST

  #Activate Playlist2
  - alias: hasp_plate01_p7_ActivatePlaylist2
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].p[4]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.spotify_PLAYLIST

  #Acitvate Playlist3
  - alias: hasp_plate01_p7_ActivatePlaylist3
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].p[5]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.spotify_PLAYLIST

  #Activate Playlist4
  - alias: hasp_plate01_p7_ActivatePlaylist4
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].p[6]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.spotify_PLAYLIST

  #Activate Playlist5
  - alias: hasp_plate01_p7_ActivatePlaylist5
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].p[7]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.spotify_PLAYLIST

  #Activate Playlist6
  - alias: hasp_plate01_p7_ActivatePlaylist6
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[7].p[8]'
      payload: 'ON'
    action:
    - service: script.turn_on
      data:
        entity_id: script.spotify_PLAYLIST
