#########################################################################
# Setup for a 3d Page
#

automation:
#########################################################################
  - alias: hasp_plate01_p9_ToggleOnOff
    trigger: 
    - platform: mqtt
      topic: 'hasp/plate01/state/p[9].[3]'
      payload: 'ON'
    action:
    - service_template: >-
        {% if is_state('switch.3d_drucker', 'off') -%}
          homeassistant.turn_on
        {%- else -%}
          homeassistant.turn_off
        {%- endif %}
      data:
        entity_id: switch.3d_drucker

#########################################################################
# Change State of ON/OFF Button
  - alias: hasp_plate01_p9_OnOffButton
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/command/page'
      payload: '9'
    - platform: state 
      entity_id: switch.3d_drucker
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/state/p[9].b[3]'
        payload_template: >-
          {% if is_state('switch.3d_drucker', 'off') -%}
            {{32}}
          {%- else %}
            {{33}}

# Represent if the 3D printer is printing or paused/off
  - alias: hasp_plate01_p9_ShowPrintingStatus
    trigger:
    - platform: state
      entity_id: sensor.octoprint_current_state
    condition:  
    - condition: state
      entity_id: 'binary_sensor.plate01_connected'
      state: 'on'
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/state/p[9].b[4]'
        payload_template: >-
          {% if is_state('sensor.octoprint_current_state', 'printing') -%}
            {{33}}
          {%-else -%}
            {{32}}
          {%- endif %}

######################################################################################
  - alias: hasp_plate01_p9_UpdateStats
    trigger:
    - platform: time_pattern
      seconds: 00
    - platform: mqtt
      topic: 'hasp/plate01/command/page'
      payload: '9'
    condition:
    - condition: state
      entity_id: switch.3d_drucker
      state: 'on'
    action:

#Display current print stats
  # Job Percentage
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/state/p[9].b[5].font'
        payload: '1'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/state/p[9].b[5].txt'
        payload_template: "{{ states.sensor.octoprint_job_percentage.state }}"
    
  # Time remaining
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/state/p[9].b[6].font'
        payload: '1'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/state/p[9].b[6].txt'
        payload_template: "{{ states.sensor.octoprint_time_remaining.state | float /60 }}"
    
  # Heatbet Temperature
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/state/p[9].b[7].font'
        payload: '1'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/state/p[9].b[7].txt'
        payload_template: '"{{ states.sensor.octoprint_actual_bed_temp.state }}/{{ states.sensor.octoprint_target_bed_temp.state }}"'
    
  # Nozzle Temperature
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/state/p[9].b[7].font'
        payload: '1'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/state/p[9].b[7].txt'
        payload_template: '"{{ states.sensor.octoprint_actual_tool0_temp.state }}/{{ states.sensor.octoprint_target_tool0_temp.state }}"'