input_number:
  hasp_plate01_00_activetoggles:
    name: 
    min: 1
    max: 9
    step: 1
    
automation:
  # Toggles Page 1
  - alias: hasp_plate01_p4_toggles1
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[3].b[4]'
      payload: 'ON'
    action:
    - service: input_number.set_value
      data_template: 
        entity_id: 'input_number.hasp_plate01_activepage'
        value: '4'
    - service: input_number.set_value
      data_template:
        entity_id: 'input_number.hasp_plate01_00_activetoggles'
        value: '1'
  # Toggles Page 2
  - alias: hasp_plate01_p4_toggles2
    trigger:
    - platform: mqtt
      topic: 'hasp/plate01/state/p[3].b[5]'
      payload: 'ON'
    action: 
    - service: input_number.set_value
      data:
        entity_id: 'input_number.hasp_plate01_activepage'
        value: '4'
    - service: input_number.set_value
      data:
        entity_id: 'input_number.hasp_plate01_activetoggles'
        value: '2'
      
      
      
      
      
      
      
      